name: clackety
description: "A lightweight typing animation widget for Flutter apps"
version: 1.0.4
homepage: https://github.com/jimmyff/clackety

environment:
  sdk: ^3.4.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
